# Generated by Django 4.1.7 on 2023-04-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytool', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tools',
            new_name='Battery',
        ),
        migrations.RenameModel(
            old_name='Batteries',
            new_name='Tool',
        ),
    ]
