# Generated by Django 4.1.7 on 2023-04-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytool', '0003_battery_amperage_battery_brand_battery_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='brushless_type',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='cordless_type',
        ),
        migrations.AddField(
            model_name='tool',
            name='brushless',
            field=models.CharField(default='yes', max_length=1),
        ),
        migrations.AddField(
            model_name='tool',
            name='cordless',
            field=models.CharField(default='yes', max_length=1),
        ),
    ]
