# Generated by Django 4.1.7 on 2023-04-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytool', '0004_remove_tool_brushless_type_remove_tool_cordless_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='brushless',
            field=models.CharField(default='yes', max_length=4),
        ),
        migrations.AlterField(
            model_name='tool',
            name='cordless',
            field=models.CharField(default='yes', max_length=4),
        ),
    ]
