# Generated by Django 4.1.7 on 2023-04-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytool', '0005_alter_tool_brushless_alter_tool_cordless'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='performance_choice',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='', help_text='Select yes if high performance battery.', max_length=1),
        ),
    ]
